apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
- cert_secret.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
- name: controller
  newName: hz-operator-dev
patchesStrategicMerge:
- manager_webhook_patch.yaml
configurations:
- kustomizeconfig.yaml
patches:
- path: disable_phone_home.yaml
  target:
    kind: Deployment
- path: remove_security_context.yaml
  target:
    kind: Deployment
