name: (E2E) Azure Tests
on:
  workflow_dispatch:
  workflow_call:

env:
  AZURE_RESOURCE_GROUP: operator-test
  GAR_REGION: us-east1
  GAR_PROJECT: hazelcast-33
  GAR_REPO: hazelcast-platform-operator
  AWS_REGION: us-east-1

jobs:
  prepare-env:
    name: Create AKS cluster
    runs-on: ubicloud-standard-2
    outputs:
      CLUSTER_NAME: ${{ steps.create-cluster.outputs.CLUSTER_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            AZURE_CREDENTIALS,CN/AZURE_CREDENTIALS

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Create AKS cluster
        id: create-cluster
        uses: azure/CLI@v2
        with:
          azcliversion: 2.31.0
          inlineScript: |
            CLUSTER_NAME="operator-e2e-test-aks-${GITHUB_SHA::8}-${{ github.run_number }}"
            echo "CLUSTER_NAME=${CLUSTER_NAME}" >> $GITHUB_OUTPUT
            NRG_NAME=$(az aks create \
              --resource-group=${AZURE_RESOURCE_GROUP} \
              --name="${CLUSTER_NAME}" \
              --node-count=3 \
              --node-vm-size Standard_D4_v2 \
              --enable-node-public-ip \
              --generate-ssh-keys | jq -r .nodeResourceGroup)
            echo "NodeResourceGroup: ${NRG_NAME}"
            echo "NRG_NAME=${NRG_NAME}" >> $GITHUB_ENV

            NSG_NAME=$(az network nsg list --resource-group=${NRG_NAME} --query='[0].name' --output=tsv)
            echo "NetworkSecurityGroup: ${NSG_NAME}"
            echo "NSG_NAME=${NSG_NAME}" >> $GITHUB_ENV

      - name: Update Network Security Group
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 1
          max_attempts: 3
          retry_on: error
          command: |
            source .github/scripts/utils.sh
            update_aks_nsg_rule "$NRG_NAME" "$NSG_NAME" AllowUbiCloudAccess

  grafana-setup:
    needs: [prepare-env]
    uses: ./.github/workflows/grafana-agent.yaml
    secrets: inherit
    with:
      cluster_name: ${{ needs.prepare-env.outputs.CLUSTER_NAME }}
      cluster_type: aks
      gh_run_id: ${{ github.run_id }}
      gh_run_number: ${{ github.run_number }}
      gh_sha: ${{ github.sha }}
      namespaces: "test-operator"

  get-image:
    name: Get Image
    runs-on: ubicloud-standard-2
    outputs:
      IMG: ${{ steps.get-image-tag.outputs.IMG }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          install: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            GKE_SA_KEY,CN/GKE_SA_KEY

      - name: Authenticate to GAR
        uses: docker/login-action@v3
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ env.GKE_SA_KEY }}

      - name: Generate Image Name
        id: get-image-tag
        run: |
          echo "IMG=${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REPO }}/$(uuidgen):5d" >> $GITHUB_OUTPUT

      - name: Build Image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            version=${{github.sha}}
            pardotID=dockerhub
          file: Dockerfile
          push: true
          tags: ${{ steps.get-image-tag.outputs.IMG }}
          cache-from: type=registry,ref=${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REPO }}/${{ hashFiles('Dockerfile','main.go','api/**','controllers/**','internal/**','licenses/**','**/go.mod','**/go.sum') }}:14d
          cache-to: type=registry,ref=${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REPO }}/${{ hashFiles('Dockerfile','main.go','api/**','controllers/**','internal/**','licenses/**','**/go.mod','**/go.sum') }}:14d

  aks-e2e-tests:
    name: Run e2e test on AKS
    runs-on: ubicloud-standard-2
    needs: ["prepare-env", "grafana-setup", "get-image"]
    defaults:
      run:
        shell: bash
    env:
      NAMESPACE: test-operator
      IMG: ${{ needs.get-image.outputs.IMG }}
      RELEASE_NAME: hp-${{ github.run_id }}
      STORAGE_CLASS: default
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.7"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            GKE_SA_KEY,CN/GKE_SA_KEY
            AZURE_CREDENTIALS,CN/AZURE_CREDENTIALS
            AZURE_STORAGE_KEY,CN/AZURE_STORAGE_KEY
            HZ_LICENSE_KEY,CN/HZ_LICENSE_KEY

      - name: Authenticate to GAR
        uses: docker/login-action@v3
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ env.GKE_SA_KEY }}

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Update kubeconfig
        run: |-
          az aks get-credentials --resource-group "${AZURE_RESOURCE_GROUP}" --name "${{ needs.prepare-env.outputs.CLUSTER_NAME }}"

      - name: Authenticate to GAR
        uses: docker/login-action@v3
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ env.GKE_SA_KEY }}

      - name: Deploy Operator to EKS
        run: |
          make install-crds
          kubectl create namespace ${NAMESPACE}
          kubectl config set-context --current --namespace=${NAMESPACE}

          DEPLOY_NAME=${RELEASE_NAME}-hazelcast-platform-operator
          make install-operator NAMESPACE=${NAMESPACE} IMG=${IMG} RELEASE_NAME=$RELEASE_NAME
          kubectl rollout status deployment $DEPLOY_NAME

      - name: Create secrets
        run: |
          kubectl create secret generic hazelcast-license-key --namespace ${NAMESPACE} \
            --from-literal=license-key=${{ env.HZ_LICENSE_KEY }}

          kubectl create secret generic br-secret-s3 --namespace ${NAMESPACE} \
            --from-literal=region=us-east-1 \
            --from-literal=access-key-id=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY }}

          kubectl create secret generic br-secret-az --namespace ${NAMESPACE} \
            --from-literal=storage-account=operatortest \
            --from-literal=storage-key=${{ env.AZURE_STORAGE_KEY }}
          
          kubectl create secret generic br-secret-gcp --namespace ${NAMESPACE} --from-literal=google-credentials-path='${{ env.GKE_SA_KEY }}'

      - name: Run Hazelcast E2E tests on EKS
        id: e2e-test
        run: |
          make test-e2e NAMESPACE=${NAMESPACE} RELEASE_NAME=$RELEASE_NAME REPORT_SUFFIX=ee_01 WORKFLOW_ID=aks STORAGE_CLASS=$STORAGE_CLASS

      - name: Check if the operator pod has not restarted
        if: always()
        run: |
          source .github/scripts/utils.sh
          assert_operator_pod_not_restarted ${NAMESPACE}

      - name: Clean up after Tests
        if: always()
        run: |
          make clean-up-namespace NAMESPACE=${NAMESPACE}

      - name: Upload Test Report
        if: always() && github.event_name != 'workflow_dispatch'
        uses: actions/upload-artifact@v3
        with:
          name: test-report-aks
          path: allure-results/aks/

  report-generation:
    needs: ["prepare-env", "aks-e2e-tests"]
    if: always() && (needs.aks-e2e-tests.result == 'success' || needs.aks-e2e-tests.result == 'failure') && github.event_name != 'workflow_dispatch'
    uses: ./.github/workflows/generate-test-report.yaml
    secrets: inherit
    with:
      WORKFLOW_ID: aks
      CLUSTER_NAME: ${{ needs.prepare-env.outputs.CLUSTER_NAME }}

  cleanup-namespaces:
    if: always()
    needs: ["prepare-env", "aks-e2e-tests"]
    uses: ./.github/workflows/cleanup-namespace.yaml
    secrets: inherit
    with:
      cluster_name: ${{ needs.prepare-env.outputs.CLUSTER_NAME }}
      cluster_type: aks
      namespaces: "test-operator,grafana"

  delete-cluster:
    name: Delete AKS cluster
    runs-on: ubicloud-standard-2
    if: always()
    needs: ["prepare-env", "aks-e2e-tests", "cleanup-namespaces"]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            AZURE_CREDENTIALS,CN/AZURE_CREDENTIALS

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Delete AKS cluster
        uses: azure/CLI@v2
        with:
          azcliversion: 2.31.0
          inlineScript: |
            az aks delete --name "${{ needs.prepare-env.outputs.CLUSTER_NAME }}" --resource-group "${AZURE_RESOURCE_GROUP}" -y

  slack_notify:
    name: Slack Notify
    needs: ["aks-e2e-tests", "delete-cluster"]
    if: always() && ( needs.aks-e2e-tests.result != 'success' || needs.delete-cluster.result != 'success')
    runs-on: ubicloud-standard-2
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            SLACK_WEBHOOK_URL,CN/SLACK_WEBHOOK_URL

      - uses: 8398a7/action-slack@v3
        with:
          fields: repo,commit,author,action,eventName,workflow
          status: failure
          channel: "#github-actions-log"
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
