name: Publish Operator Snapshot
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - ".github"

env:
  AWS_REGION: us-east-1
  REGISTRY_IMAGE: hazelcast/hazelcast-platform-operator

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_snapshot_image:
    name: Build Operator Snapshot
    runs-on: ubicloud-standard-2
    outputs:
      AMD64_DIGEST: ${{ steps.digest.outputs.AMD64_DIGEST }}
      ARM64_DIGEST: ${{ steps.digest.outputs.ARM64_DIGEST }}
      S390X_DIGEST: ${{ steps.digest.outputs.S390X_DIGEST }}
      PPC64LE_DIGEST: ${{ steps.digest.outputs.PPC64LE_DIGEST }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          [ "arm64", "amd64", "s390x", "ppc64le" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set Up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.7.1
        with:
          install: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            DOCKERHUB_USERNAME,CN/DOCKERHUB_USERNAME
            DOCKERHUB_PASSWORD,CN/DOCKERHUB_PASSWORD
            DEVOPS_GITHUB_TOKEN,CN/DEVOPS_GITHUB_TOKEN

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build Operator Image
        id: build
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            version=latest-snapshot
            pardotID=dockerhub
          file: Dockerfile
          platforms: linux/${{ matrix.arch }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          labels: |
            operator.image.revision=${{github.sha}}

      - name: Save Digest
        id: digest
        run: |
          if [ "${{ matrix.arch }}" == "amd64" ]; then
            echo "AMD64_DIGEST=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.arch }}" == "arm64" ]; then
            echo "ARM64_DIGEST=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.arch }}" == "s390x" ]; then
            echo "S390X_DIGEST=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.arch }}" == "ppc64le" ]; then
            echo "PPC64LE_DIGEST=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT
          fi

      - name: Generate API Reference Docs
        run: |
          make api-ref-doc > api-ref.adoc

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: hazelcast/hazelcast-platform-operator-docs
          ref: main
          token: ${{ env.DEVOPS_GITHUB_TOKEN }}
          path: docs-repo

      - name: Push API Reference to Docs repo
        working-directory: docs-repo
        run: |
          git config user.email "devopshelm@hazelcast.com"
          git config user.name "devOpsHelm"
          
          if cmp -s ../api-ref.adoc docs/modules/ROOT/pages/api-ref.adoc; then
              echo "No need to update API Reference doc"
              exit 0
          fi
          mv ../api-ref.adoc docs/modules/ROOT/pages/api-ref.adoc
          git add docs/modules/ROOT/pages/api-ref.adoc
          git commit -m "Update API reference doc" && git push origin main

  publish_snapshot_image:
    needs: build_snapshot_image
    name: Publish Snapshot
    runs-on: ubicloud-standard-2
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            DOCKERHUB_USERNAME,CN/DOCKERHUB_USERNAME
            DOCKERHUB_PASSWORD,CN/DOCKERHUB_PASSWORD

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Push The Multi-Arch Image
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ env.REGISTRY_IMAGE }}:latest-snapshot
          sources: |
            ${{ env.REGISTRY_IMAGE }}@${{ needs.build_snapshot_image.outputs.AMD64_DIGEST }}
            ${{ env.REGISTRY_IMAGE }}@${{ needs.build_snapshot_image.outputs.ARM64_DIGEST }}
            ${{ env.REGISTRY_IMAGE }}@${{ needs.build_snapshot_image.outputs.S390X_DIGEST }}
            ${{ env.REGISTRY_IMAGE }}@${{ needs.build_snapshot_image.outputs.PPC64LE_DIGEST }}

  slack_notify:
    name: Slack Notify
    needs: [ 'publish_snapshot_image' ]
    if: always() &&  needs.publish_snapshot_image.result != 'success' 
    runs-on: ubicloud-standard-2
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            SLACK_WEBHOOK_URL,CN/SLACK_WEBHOOK_URL

      - uses: 8398a7/action-slack@v3
        with:
          fields: repo,commit,author,action,eventName,workflow
          status: failure
          channel: "#github-actions-log"
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}

