name: Publish Agent Snapshot
on:
  push:
    branches:
      - main
    paths:
      - "agent/**"

env:
  AWS_REGION: us-east-1

jobs:
  publish-snapshot-image:
    name: Publish Agent Snapshot to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set Up Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"

      - name: Set Up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          install: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            DOCKERHUB_USERNAME,CN/DOCKERHUB_USERNAME
            DOCKERHUB_PASSWORD,CN/DOCKERHUB_PASSWORD

      - name: Set Up Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.7"

      - name: Set Up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and Push Operator Agent Image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: agent/Dockerfile
          push: true
          tags: hazelcast/platform-operator-agent:latest-snapshot
          platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
          labels: |
            agent.image.revision=${{ github.sha }}

  slack_notify:
    name: Slack Notify
    needs: ["publish-snapshot-image"]
    if: always() &&  needs.publish-snapshot-image.result != 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            SLACK_WEBHOOK_URL,CN/SLACK_WEBHOOK_URL

      - uses: 8398a7/action-slack@v3
        with:
          fields: repo,commit,author,action,eventName,workflow
          status: failure
          channel: "#github-actions-log"
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}