name: Vulnerability Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  operator-scan:
    name: Operator Scan
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
          - category: image
            scan-type: image
            image-ref: docker.io/hazelcast/hazelcast-platform-operator:latest-snapshot
          - category: repo
            scan-type: repo
            image-ref: ''
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Operator Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.23.0
        with:
          scan-type: '${{ matrix.scan-type }}'
          image-ref: '${{ matrix.image-ref }}'
          ignore-unfixed: true
          limit-severities-for-sarif: true
          format: 'table'
          exit-code: '1'
          output: ${{ matrix.category }}.txt
          severity: 'CRITICAL,HIGH'

      - name: Publish Trivy Output to Summary
        if: always()
        run: |
          {
            echo "### Operator ${{ matrix.category }} scan"
            echo "<details><summary>Click to expand</summary>"
            echo ""
            echo '```${{ matrix.category }}'
            cat ${{ matrix.category }}.txt
            echo '```'
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY